#!/usr/bin/env bash
set -euo pipefail

export DBTOOL_IT_PROJECT="${DBTOOL_IT_PROJECT:-dbtool-it}"

export DBTOOL_IT_POSTGRES_DB="${DBTOOL_IT_POSTGRES_DB:-dbtool_it_pg}"
export DBTOOL_IT_POSTGRES_USER="${DBTOOL_IT_POSTGRES_USER:-dbtool}"
export DBTOOL_IT_POSTGRES_PASSWORD="${DBTOOL_IT_POSTGRES_PASSWORD:-dbtool}"
export DBTOOL_IT_POSTGRES_PORT="${DBTOOL_IT_POSTGRES_PORT:-15432}"

export DBTOOL_IT_MYSQL_DB="${DBTOOL_IT_MYSQL_DB:-dbtool_it_mysql}"
export DBTOOL_IT_MYSQL_USER="${DBTOOL_IT_MYSQL_USER:-dbtool}"
export DBTOOL_IT_MYSQL_PASSWORD="${DBTOOL_IT_MYSQL_PASSWORD:-dbtool}"
export DBTOOL_IT_MYSQL_ROOT_PASSWORD="${DBTOOL_IT_MYSQL_ROOT_PASSWORD:-dbtool_root}"
export DBTOOL_IT_MYSQL_PORT="${DBTOOL_IT_MYSQL_PORT:-13306}"

export DBTOOL_IT_REDIS_PORT="${DBTOOL_IT_REDIS_PORT:-16379}"

export DBTOOL_IT_MONGO_DB="${DBTOOL_IT_MONGO_DB:-dbtool_it_mongo}"
export DBTOOL_IT_MONGO_USER="${DBTOOL_IT_MONGO_USER:-dbtool}"
export DBTOOL_IT_MONGO_PASSWORD="${DBTOOL_IT_MONGO_PASSWORD:-dbtool}"
export DBTOOL_IT_MONGO_PORT="${DBTOOL_IT_MONGO_PORT:-17017}"

export DBTOOL_IT_POSTGRES_DSN="${DBTOOL_IT_POSTGRES_DSN:-postgres://${DBTOOL_IT_POSTGRES_USER}:${DBTOOL_IT_POSTGRES_PASSWORD}@127.0.0.1:${DBTOOL_IT_POSTGRES_PORT}/${DBTOOL_IT_POSTGRES_DB}}"
export DBTOOL_IT_MYSQL_DSN="${DBTOOL_IT_MYSQL_DSN:-mysql://${DBTOOL_IT_MYSQL_USER}:${DBTOOL_IT_MYSQL_PASSWORD}@127.0.0.1:${DBTOOL_IT_MYSQL_PORT}/${DBTOOL_IT_MYSQL_DB}}"
export DBTOOL_IT_REDIS_DSN="${DBTOOL_IT_REDIS_DSN:-redis://127.0.0.1:${DBTOOL_IT_REDIS_PORT}/0}"
export DBTOOL_IT_MONGO_DSN="${DBTOOL_IT_MONGO_DSN:-mongodb://${DBTOOL_IT_MONGO_USER}:${DBTOOL_IT_MONGO_PASSWORD}@127.0.0.1:${DBTOOL_IT_MONGO_PORT}/${DBTOOL_IT_MONGO_DB}?authSource=admin}"
